FROM ubuntu

RUN apt-get update && apt-get install -y python3 python3-pip && apt-get clean

RUN pip3 install requests numpy pandas flask psycopg2-binary

RUN adduser --home /app azdo

USER azdo

COPY hello.py /app/

ENTRYPOINT /app/hello.py
