FROM ubuntu

RUN apt-get update && apt-get install -y python3 python3-pip && apt-get clean

WORKDIR /app

RUN pip install requests
RUN pip install numpy
RUN pip install pandas
RUN pip install flask
RUN pip install psycopg2-binary

RUN adduser --home /app azdo

USER azdo

COPY hello.py /app/

ENTRYPOINT /app/hello.py
